version: "3.8"
services:
  ev-charger:
    build: .
    container_name: smart_ev_charger
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./service_account.json:/app/service_account.json:ro